# -*- coding: utf-8 -*-
"""自主研究循环 v2 测试 — run_autonomous_research_loop_v2 / build_autonomous_research_report_v2 的只读测试。"""

from __future__ import annotations
import sys, unittest
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
if str(PROJECT_ROOT) not in sys.path: sys.path.insert(0, str(PROJECT_ROOT))

from northstar.data.recommendation_review import (
    run_autonomous_research_loop_v2,
    build_autonomous_research_report_v2,
    _generate_research_topics,
)


class TestAutonomousResearchV2(unittest.TestCase):
    def test_empty_no_crash(self):
        """空数据不崩溃"""
        r = run_autonomous_research_loop_v2([])
        self.assertIn("research_cycle", r)
        self.assertIn("next_research_questions", r)
        self.assertIn("system_conclusions", r)
        self.assertIn("confidence", r)

    def test_report_empty_no_crash(self):
        """报告空数据不崩溃"""
        r = build_autonomous_research_report_v2([])
        self.assertIn("core_insights", r)
        self.assertIn("research_evolution", r)
        self.assertIn("recommended_next_cycle", r)
        self.assertIn("confidence", r)

    def test_cycle_generated(self):
        """给定足够数据应生成 research cycle"""
        rows = [
            {"action": "buy", "price": 100, "current_price": 105, "change_pct": 5.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 106, "change_pct": 6.0, "review_grade": "有效"},
            {"action": "sell", "price": 100, "current_price": 95, "change_pct": -5.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 108, "change_pct": 8.0, "review_grade": "有效"},
            {"action": "sell", "price": 100, "current_price": 92, "change_pct": -8.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 103, "change_pct": 3.0, "review_grade": "有效"},
        ]
        r = run_autonomous_research_loop_v2(rows)
        self.assertGreater(len(r["research_cycle"]), 0)

    def test_topic_autogenerated(self):
        """topic 应自动生成"""
        rows = [
            {"action": "buy", "price": 100, "current_price": 105, "change_pct": 5.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 106, "change_pct": 6.0, "review_grade": "有效"},
            {"action": "sell", "price": 100, "current_price": 95, "change_pct": -5.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 108, "change_pct": 8.0, "review_grade": "有效"},
            {"action": "sell", "price": 100, "current_price": 92, "change_pct": -8.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 103, "change_pct": 3.0, "review_grade": "有效"},
        ]
        topics = _generate_research_topics(rows)
        for t in topics:
            self.assertIn("topic", t)
            self.assertIn("source", t)
            self.assertIn("reason", t)

    def test_analysis_path_complete(self):
        """analysis_path 应包含 3-4 步"""
        rows = [
            {"action": "buy", "price": 100, "current_price": 105, "change_pct": 5.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 106, "change_pct": 6.0, "review_grade": "有效"},
            {"action": "sell", "price": 100, "current_price": 95, "change_pct": -5.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 108, "change_pct": 8.0, "review_grade": "有效"},
            {"action": "sell", "price": 100, "current_price": 92, "change_pct": -8.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 103, "change_pct": 3.0, "review_grade": "有效"},
        ]
        r = run_autonomous_research_loop_v2(rows)
        for c in r["research_cycle"]:
            self.assertGreater(len(c["analysis_path"]), 0)

    def test_insight_non_empty(self):
        """insight 应非空"""
        rows = [
            {"action": "buy", "price": 100, "current_price": 105, "change_pct": 5.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 106, "change_pct": 6.0, "review_grade": "有效"},
            {"action": "sell", "price": 100, "current_price": 95, "change_pct": -5.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 108, "change_pct": 8.0, "review_grade": "有效"},
            {"action": "sell", "price": 100, "current_price": 92, "change_pct": -8.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 103, "change_pct": 3.0, "review_grade": "有效"},
        ]
        r = run_autonomous_research_loop_v2(rows)
        for c in r["research_cycle"]:
            self.assertIsNotNone(c.get("insight"))
            self.assertGreater(len(c["insight"]), 0)

    def test_next_questions_generated(self):
        """next_research_questions 应生成"""
        rows = [
            {"action": "buy", "price": 100, "current_price": 105, "change_pct": 5.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 106, "change_pct": 6.0, "review_grade": "有效"},
            {"action": "sell", "price": 100, "current_price": 95, "change_pct": -5.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 108, "change_pct": 8.0, "review_grade": "有效"},
            {"action": "sell", "price": 100, "current_price": 92, "change_pct": -8.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 103, "change_pct": 3.0, "review_grade": "有效"},
        ]
        r = run_autonomous_research_loop_v2(rows)
        self.assertIsInstance(r["next_research_questions"], list)

    def test_confidence_in_range(self):
        """confidence 应在 0~1 之间"""
        rows = [
            {"action": "buy", "price": 100, "current_price": 105, "change_pct": 5.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 106, "change_pct": 6.0, "review_grade": "有效"},
            {"action": "sell", "price": 100, "current_price": 95, "change_pct": -5.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 108, "change_pct": 8.0, "review_grade": "有效"},
            {"action": "sell", "price": 100, "current_price": 92, "change_pct": -8.0, "review_grade": "有效"},
            {"action": "buy", "price": 100, "current_price": 103, "change_pct": 3.0, "review_grade": "有效"},
        ]
        r = run_autonomous_research_loop_v2(rows)
        self.assertGreaterEqual(r["confidence"], 0.0)
        self.assertLessEqual(r["confidence"], 1.0)


if __name__ == "__main__":
    unittest.main()